### ISSUE TITLE
'RegistrationData' object has no attribute 'use_rri'

### ISSUE THREAD

**Issue by Chenliezhen259** [vinits5/learning3d#16]
Hi, when i run **test_pnlk.py** , it showed:

**Traceback (most recent call last):**
  File "test_pnlk.py", line 121, in <module>
    main()
  File "test_pnlk.py", line 118, in main
    test(args, model, test_loader)
  File "test_pnlk.py", line 61, in test
    test_loss, test_accuracy = test_one_epoch(args.device, model, test_loader)
  File "test_pnlk.py", line 42, in test_one_epoch
    for i, data in enumerate(tqdm(test_loader)):
  File ".../miniconda3/envs/pytorch-point/lib/python3.7/site-packages/tqdm/std.py", line 1195, in \__iter__
    for obj in iterable:
  File ".../miniconda3/envs/pytorch-point/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in \__next__
    data = self._next_data()
  File ".../miniconda3/envs/pytorch-point/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File ".../miniconda3/envs/pytorch-point/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File ".../miniconda3/envs/pytorch-point/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
**AttributeError: Caught AttributeError in DataLoader worker process 0.**
**Original Traceback (most recent call last):**
  File ".../miniconda3/envs/pytorch-point/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File ".../miniconda3/envs/pytorch-point/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File ".../miniconda3/envs/pytorch-point/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File ".../learning3d/data_utils/dataloaders.py", line 257, in \___getitem\___
    if self.use_rri:
**AttributeError: 'RegistrationData' object has no attribute 'use_rri'**

somesone said that maybe because of the version of the pytorch and torchvision.
My pytorch: 1.7.1, torchvision: 0.8.2
Could you tell me your environment setting?
or
How to do i could solve it?

Thanks！

**Comment by Chenliezhen259** [comment]
By the way，when  i run test_pointnet.py, it was worked.
