### ISSUE TITLE
Possible error with Masknet?

### ISSUE THREAD

**Issue by kidpaul94** [vinits5/learning3d#8]
Hi, thank you for your great work @vinits5! I'm looking forward to test Masknet on my own RGBD data.
I just encountered this following issue when running test_masknet.py in Google colab:

https://github.com/vinits5/learning3d/blob/45bebb79f11aa46c2464a754fa379f66e4102acb/examples/test_masknet.py#L21
    
    Error raised in pointnet2 module in utils!
    Either don't use pointnet2_utils or retry it's setup.
    INFO - 2021-05-17 01:41:24,679 - ppfnet - Using early fusion, feature dim = 96
    INFO - 2021-05-17 01:41:24,680 - ppfnet - Feature extraction using features xyz, dxyz, ppf
    Traceback (most recent call last):
      File "test_masknet.py", line 21, in <module>
        from learning3d.models import MaskNet
      File "/content/drive/MyDrive/learning3d/models/__init__.py", line 16, in <module>
        from .deepgmr import DeepGMR
      File "/content/drive/MyDrive/learning3d/models/deepgmr.py", line 162
        'r': template_features - source_features,
          ^
    SyntaxError: invalid syntax 

I'm not exactly sure whether this syntax error was already there, or something happened because I tried to modify some part of test_masknet.py so that I can directly feed .ply file (instead of using .hdf5 format):

**Comment by kidpaul94** [comment]
https://github.com/vinits5/learning3d/blob/45bebb79f11aa46c2464a754fa379f66e4102acb/models/deepgmr.py#L161
Comma is missing in between line 161 and 162.

**Comment by kidpaul94** [comment]
Ok, there are some errors in directory setting: 

https://github.com/vinits5/learning3d/blob/45bebb79f11aa46c2464a754fa379f66e4102acb/examples/test_masknet.py#L21

This line should be like, "from models import MaskNet" and same for the "data_utils"

https://github.com/vinits5/learning3d/blob/45bebb79f11aa46c2464a754fa379f66e4102acb/models/deepgmr.py#L10

Also, all ".." in front of ops and utils when importing them should be removed for all model.py

**Comment by kidpaul94** [comment]
Ok, I understood the problem. My fragment pc is deviated too much in terms of rotation from the reference pc.
